ports:
    - port: 3000
      onOpen: open-preview
    - port: 3306
      onOpen: ignore
tasks:
    - init: >
        cp .env.example .env;
        pipenv install;
        mysql -u root -e "CREATE DATABASE example";
        pipenv run init;
        pipenv run migrate;
        pipenv run upgrade;
    - init: >
        npm i now -g &&
        npm install &&
        cp .env.example .env
      openMode: split-right