ports:
    - port: 3000
      onOpen: open-preview
    - port: 3306
      onOpen: ignore
tasks:
    - init: >
        cp .env.example .env;
        echo "" >> .env && echo "BACKEND_URL=https://3001-${GITPOD_WORKSPACE_URL:8}" >> .env;
        npm install;
        pipenv install;
        mysql -u root -e "CREATE DATABASE example";
        pipenv run init;
        pipenv run migrate;
        pipenv run upgrade;
    - command: >
        cat << EOF
        Hello! This terminal will represent your backend!
        1. Get inside the environment $ pipenv shell
        2. Start the server by typing $ pipenv run start
        EOF
    - command: >
        cat << EOF
        This terminal is for front-end!
        1. Start webpack dev server $ npm run start
        EOF
      openMode: split-right