"""empty message

Revision ID: 2286a89bea59
Revises: b86d3e5cd485
Create Date: 2021-02-18 15:54:37.123563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2286a89bea59'
down_revision = 'b86d3e5cd485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_company_User_Id_fkey', 'user_company', type_='foreignkey')
    op.create_foreign_key(None, 'user_company', 'user', ['user_id'], ['id'])
    op.drop_column('user_company', 'User_Id')
    op.add_column('user_psychologyst', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_psychologyst_User_Id_fkey', 'user_psychologyst', type_='foreignkey')
    op.create_foreign_key(None, 'user_psychologyst', 'user', ['user_id'], ['id'])
    op.drop_column('user_psychologyst', 'User_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_psychologyst', sa.Column('User_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_psychologyst', type_='foreignkey')
    op.create_foreign_key('user_psychologyst_User_Id_fkey', 'user_psychologyst', 'user', ['User_Id'], ['id'])
    op.drop_column('user_psychologyst', 'user_id')
    op.add_column('user_company', sa.Column('User_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_company', type_='foreignkey')
    op.create_foreign_key('user_company_User_Id_fkey', 'user_company', 'user', ['User_Id'], ['id'])
    op.drop_column('user_company', 'user_id')
    op.drop_column('category', 'is_active')
    # ### end Alembic commands ###
