"""empty message

Revision ID: 273aa00d5647
Revises: 03527bd9a6eb
Create Date: 2021-02-21 12:37:06.277621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273aa00d5647'
down_revision = '03527bd9a6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('linkedIn', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('youTube', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'youTube')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'linkedIn')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    # ### end Alembic commands ###
