"""empty message

Revision ID: 392187d8c586
Revises: 22e5c6e598fc
Create Date: 2021-02-21 12:43:47.003361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392187d8c586'
down_revision = '22e5c6e598fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_workshop', 'max_people',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('facebook', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('linkedIn', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('youTube', sa.String(length=250), nullable=True))
    op.alter_column('user', 'is_psychologist',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_psychologist',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'youTube')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'linkedIn')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    op.alter_column('search_workshop', 'max_people',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
