"""empty message

Revision ID: 79432626bb1e
Revises: 3f53491a1657
Create Date: 2021-02-27 17:21:51.368782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79432626bb1e'
down_revision = '3f53491a1657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
