data = {
    "Search_workshop":[{
        "id": 1,
	    "duration": "20 hours",
	    "price": 550,
	    "date": "2021/4/19",
	    "max_people": 10,
	    "category_id": 10,
        "user_company_id": 2, 
        "is_active": True,
    },
    {
        "id": 2,
	    "duration": "15 hours",
	    "price": 400,
	    "date": "2021/4/21",
	    "max_people": 12,
	    "category_id": 2,
        "user_company_id": 1, 
        "is_active": True,
    },
   {
        "id": 3,
	    "duration": "40 hours",
	    "price": 950,
	    "date": "2021/3/24",
	    "max_people": 15,
	    "category_id": 3,
        "user_company_id": 3, 
        "is_active": True,
    },
    {
        "id": 4,
	    "duration": "20 hours",
	    "price": 600,
	    "date": "2021/3/24",
	    "max_people": 10,
	    "category_id": 4,
        "user_company_id": 3, 
        "is_active": True,
    },
    {
        "id": 5,
	    "duration": "80 hours",
	    "price": 1600,
	    "date": "2021/5/19",
	    "max_people": 15,
	    "category_id": 7,
        "user_company_id": 5, 
        "is_active": True,
    },
    {
        "id": 6,
	    "duration": "10 hours",
	    "price": 350,
	    "date": "2021/4/10",
	    "max_people": 5,
	    "category_id": 7,
        "user_company_id": 1, 
        "is_active": True,
    },
    {
        "id": 7,
	    "duration": "160 hours",
	    "price": 1350,
	    "date": "2021/6/1",
	    "max_people": 18,
	    "category_id": 4,
        "user_company_id": 4, 
        "is_active": True,
    },
    {
        "id": 8,
	    "duration": "25 hours",
	    "price": 600,
	    "date": "2021/5/23",
	    "max_people": 12,
	    "category_id": 6,
        "user_company_id": 5, 
        "is_active": True,
    },
    {
        "id": 9,
	    "duration": "20 hours",
	    "price": 550,
	    "date": "2021/4/15",
	    "max_people": 10,
	    "category_id": 10,
        "user_company_id": 1, 
        "is_active": True,
    },
    {
        "id": 10,
	    "duration": "30 hours",
	    "price": 700,
	    "date": "2021/6/19",
	    "max_people": 8,
	    "category_id": 9,
        "user_company_id": 5, 
        "is_active": True,
    },
    ],

    "User_company": [{
        "id": 1,
        "company_name": "4 Geeks Academy",
        "company_number": "B-00000001",
        "user_id": 6,
    },
    {
        "id": 2,
        "company_name": "Ravenloop",
        "company_number": "B-00000002",
        "user_id": 7,
    },
    {
        "id": 3,
        "company_name": "TalentHackers",
        "company_number": "B-00000003",
        "user_id": 8,
    },
    {
        "id": 4,
        "company_name": "Modis",
        "company_number": "B-00000004",
        "user_id": 9,
    },
    {
        "id": 5,
        "company_name": "Amazon",
        "company_number": "B-00000005",
        "user_id": 10,
    },
    ]
}